import Head from 'next/head'
import Navbar from "./Navbar";
import Footer from "./Footer";




export default function Layout({children}) {
  return (
    <div>
        <Head>
            <title>Foodhero</title>
            <meta name="description" content="Generated by Hristos Pappas" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <div className='container'>
        {children}
        </div>
        <Footer />
    </div>
  )
}
